#!/usr/bin/env python3
"""Unit tests for the shared suite harness.

Standard library only, and needs no running stack. This is the one suite in
`suites/` that tests the test infrastructure rather than the driver.
"""

import io
import os
import sys
import tempfile
import unittest
from contextlib import redirect_stdout

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from harness import Results, Stack  # noqa: E402


class TestResults(unittest.TestCase):
    def test_ok_counts_and_prints_pass(self):
        r = Results("t")
        out = io.StringIO()
        with redirect_stdout(out):
            r.ok("a thing")
        self.assertEqual(r.passed, 1)
        self.assertEqual(r.failed, 0)
        self.assertIn("PASS  a thing", out.getvalue())

    def test_bad_counts_and_prints_fail_with_detail(self):
        r = Results("t")
        out = io.StringIO()
        with redirect_stdout(out):
            r.bad("a thing", "because reasons")
        self.assertEqual(r.failed, 1)
        self.assertIn("FAIL  a thing: because reasons", out.getvalue())

    def test_check_returns_its_condition(self):
        r = Results("t")
        with redirect_stdout(io.StringIO()):
            self.assertTrue(r.check("yes", True))
            self.assertFalse(r.check("no", False))
        self.assertEqual((r.passed, r.failed), (1, 1))

    def test_run_records_a_raising_callable_as_a_failure(self):
        r = Results("t")
        out = io.StringIO()
        with redirect_stdout(out):
            r.run("explodes", lambda: (_ for _ in ()).throw(ValueError("boom")))
        self.assertEqual(r.failed, 1)
        self.assertIn("boom", out.getvalue())

    def test_run_prints_elapsed_time(self):
        r = Results("t")
        out = io.StringIO()
        with redirect_stdout(out):
            r.run("quick", lambda: None)
        self.assertEqual(r.passed, 1)
        self.assertRegex(out.getvalue(), r"PASS  quick  \(\d+\.\ds\)")

    def test_skip_is_counted_separately_and_names_a_reason(self):
        r = Results("t")
        out = io.StringIO()
        with redirect_stdout(out):
            r.skip("tls", "profile 'oauth' is not active")
        self.assertEqual((r.passed, r.failed, r.skipped), (0, 0, 1))
        self.assertIn("SKIP  tls: profile 'oauth' is not active", out.getvalue())

    def test_note_is_neither_pass_nor_fail(self):
        r = Results("t")
        with redirect_stdout(io.StringIO()):
            r.note("observation", "a statement may be allocated before connecting")
        self.assertEqual((r.passed, r.failed, r.notes), (0, 0, 1))

    def test_summary_exit_code_is_zero_only_when_nothing_failed(self):
        r = Results("t")
        with redirect_stdout(io.StringIO()):
            r.ok("a")
            self.assertEqual(r.summary(), 0)
            r.bad("b")
            self.assertEqual(r.summary(), 1)

    def test_summary_reports_skips_so_they_cannot_read_as_passes(self):
        r = Results("t")
        out = io.StringIO()
        with redirect_stdout(out):
            r.ok("a")
            r.skip("b", "no profile")
            r.summary()
        self.assertIn("1 passed, 0 failed, 1 skipped", out.getvalue())


STACK_ENV = """\
# generated by scripts/gen-odbc-config.sh, do not edit
DRIVER_PATH=/tmp/libstackable_odbc_trino.so
TRINO_HOST=localhost
TRINO_HTTPS_PORT=8443
TRINO_USER=admin
TRINO_PASSWORD=admin
TRINO_CATALOG=tpcds
CA_CERT=/tmp/certs/ca.crt
CLIENT_PEM="/tmp/certs/client.pem"
PROFILES=oauth,spooling
"""


class TestStack(unittest.TestCase):
    def setUp(self):
        fd, self.path = tempfile.mkstemp(suffix=".env")
        with os.fdopen(fd, "w") as f:
            f.write(STACK_ENV)
        self.addCleanup(os.unlink, self.path)
        self.stack = Stack.load(self.path)

    def test_comments_and_blank_lines_are_ignored(self):
        self.assertIsNone(self.stack.get("# generated by scripts/gen-odbc-config.sh"))
        self.assertEqual(self.stack.get("TRINO_HOST"), "localhost")

    def test_quoted_values_are_unquoted(self):
        self.assertEqual(self.stack.get("CLIENT_PEM"), "/tmp/certs/client.pem")

    def test_missing_key_returns_the_default(self):
        self.assertEqual(self.stack.get("NOPE", "fallback"), "fallback")

    def test_profiles_split_on_comma(self):
        self.assertEqual(self.stack.profiles, ["oauth", "spooling"])
        self.assertTrue(self.stack.has_profile("spooling"))
        self.assertFalse(self.stack.has_profile("nosuchprofile"))

    def test_empty_profiles_is_an_empty_list_not_a_list_containing_empty(self):
        with open(self.path, "a") as f:
            f.write("PROFILES=\n")
        self.assertEqual(Stack.load(self.path).profiles, [])

    def test_conn_str_defaults_to_https_with_the_ca(self):
        cs = self.stack.conn_str()
        self.assertIn("Driver=/tmp/libstackable_odbc_trino.so", cs)
        self.assertIn("Host=localhost", cs)
        self.assertIn("Port=8443", cs)
        self.assertIn("Protocol=https", cs)
        self.assertIn("Certificate=/tmp/certs/ca.crt", cs)
        self.assertIn("Catalog=tpcds", cs)

    def test_conn_str_override_replaces_a_value(self):
        self.assertIn("Catalog=postgresql", self.stack.conn_str(Catalog="postgresql"))

    def test_conn_str_override_of_none_removes_the_key(self):
        cs = self.stack.conn_str(Password=None)
        self.assertNotIn("Password=", cs)
        self.assertIn("User=admin", cs)

    def test_conn_str_adds_a_key_that_has_no_default(self):
        cs = self.stack.conn_str(TlsVerify="ca")
        self.assertIn("TlsVerify=ca", cs)

    def test_conn_str_is_semicolon_separated_with_no_trailing_separator(self):
        cs = self.stack.conn_str()
        self.assertFalse(cs.endswith(";"))
        self.assertNotIn(";;", cs)

    def test_dsn_string_carries_only_the_dsn(self):
        self.assertEqual(self.stack.dsn("trino_https"), "DSN=trino_https")

    def test_a_missing_stack_env_names_the_command_that_writes_it(self):
        with self.assertRaises(SystemExit) as caught:
            Stack.load("/nonexistent/stack.env")
        self.assertIn("setup.sh", str(caught.exception))


if __name__ == "__main__":
    unittest.main()
