#!/usr/bin/env bash
# Writes odbcinst.ini, odbc.ini and stack.env into generated/.
set -euo pipefail
# shellcheck source-path=SCRIPTDIR source=lib.sh
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib.sh"

# The certificate the coordinator is verified against: the test CA, which
# signed the coordinator's leaf.
SERVER_CERT="$CERT_DIR/ca.crt"

# Threading = 2 must match packaging/linux/install.sh -- see the comment there.
# unixODBC's default of 3 serialises a cross-thread SQLCancel behind the call it
# was meant to interrupt, which is a configuration no user has.
# test_integration.py's cross-thread cancel test is what notices.
cat > "$GENERATED/odbcinst.ini" << EOF
[stackable_odbc_trino]
Driver = $DRIVER_PATH
Threading = 2
EOF

cat > "$GENERATED/odbc.ini" << EOF
[trino_https]
Driver = stackable_odbc_trino
Host = $TRINO_HOST
Port = $TRINO_HTTPS_PORT
User = $TRINO_USER
Password = $TRINO_PASSWORD
Protocol = https
Catalog = $TRINO_CATALOG
Certificate = $SERVER_CERT

[trino_https_verify_false]
Driver = stackable_odbc_trino
Host = $TRINO_HOST
Port = $TRINO_HTTPS_PORT
User = $TRINO_USER
Password = $TRINO_PASSWORD
Protocol = https
Catalog = $TRINO_CATALOG
TlsVerify = false

[trino_postgresql]
Driver = stackable_odbc_trino
Host = $TRINO_HOST
Port = $TRINO_HTTPS_PORT
User = $TRINO_USER
Password = $TRINO_PASSWORD
Protocol = https
Catalog = postgresql
Certificate = $SERVER_CERT
EOF

# One description of the running stack. Bash sources it; harness.Stack parses
# it. Every connection string in every suite is built from here, so a port, a
# credential or a certificate path is stated once.
cat > "$STACK_ENV" << EOF
# generated by scripts/gen-odbc-config.sh -- do not edit
DRIVER_PATH=$DRIVER_PATH
TRINO_HOST=$TRINO_HOST
TRINO_HTTPS_PORT=$TRINO_HTTPS_PORT
TRINO_USER=$TRINO_USER
TRINO_PASSWORD=$TRINO_PASSWORD
TRINO_CATALOG=$TRINO_CATALOG
CA_CERT=$SERVER_CERT
CLIENT_PEM=$CERT_DIR/client.pem
ODBCSYSINI=$GENERATED
ODBCINI=$GENERATED/odbc.ini
PROFILES=${PROFILES:-}
EOF

echo "Wrote odbcinst.ini, odbc.ini and stack.env to $GENERATED"
