//! ODBC driver for [Trino](https://trino.io), built on the generic
//! [`stackable_odbc_core`] framework.
//!
//! This crate compiles to a C dynamic library (`cdylib`) that an ODBC Driver
//! Manager (unixODBC on Linux, the built-in DM on Windows) loads at runtime —
//! it is not used as a normal Rust dependency. All the ODBC C ABI entry points
//! are generated by [`stackable_odbc_core::forward_ffi!`] from the [`TrinoBackend`]
//! implementation; the Driver Manager translates ANSI calls, so only the
//! Unicode (`W`) functions are exported.
//!
//! The backend speaks to a Trino coordinator over its HTTP REST protocol via
//! `trino-rust-client`, wrapping an internal Tokio runtime because the
//! [`stackable_odbc_core::backend::Backend`] trait is synchronous. Connection-string
//! keys (`Host`, `Port`, `User`, `Password`, `Protocol`, `Catalog`, `Schema`,
//! TLS and JWT options) are parsed from the ODBC connection string.

mod backend;
mod escape_dialect;
mod type_conversion;

pub use backend::TrinoBackend;

stackable_odbc_core::forward_ffi!(crate::backend::TrinoBackend);

#[cfg(test)]
mod ffi_integration_tests;
